import type { User, Lecture, Notification } from './types';

export const users: (User & { password?: string })[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@classpal.com',
    password: 'password',
    role: 'admin',
    avatarUrl: 'https://picsum.photos/seed/admin/100/100',
  },
  {
    id: '2',
    name: 'Dr. Eleanor Vance',
    email: 'teacher@classpal.com',
    password: 'password',
    role: 'teacher',
    avatarUrl: 'https://picsum.photos/seed/teacher/100/100',
  },
  {
    id: '3',
    name: 'Alex Johnson',
    email: 'student@classpal.com',
    password: 'password',
    role: 'student',
    avatarUrl: 'https://picsum.photos/seed/student/100/100',
  },
];

export const lectures: Lecture[] = [
  {
    id: 'L001',
    subject: 'Quantum Physics',
    code: 'PHY301',
    teacher: 'Dr. Eleanor Vance',
    teacherId: '2',
    classroom: 'Room 101',
    day: 'Monday',
    startTime: '09:00',
    endTime: '10:30',
    status: 'confirmed',
    forRoles: ['admin', 'teacher', 'student'],
    students: [
      { studentId: '3', attendanceRate: 0.9, missedSessions: 1 },
      { studentId: 'S002', attendanceRate: 0.95, missedSessions: 0 },
      { studentId: 'S003', attendanceRate: 0.7, missedSessions: 3 },
    ],
  },
  {
    id: 'L002',
    subject: 'Advanced Algorithms',
    code: 'CS402',
    teacher: 'Dr. Ben Carter',
    teacherId: '4',
    classroom: 'Room 202',
    day: 'Tuesday',
    startTime: '11:00',
    endTime: '12:30',
    status: 'confirmed',
    forRoles: ['admin', 'student'],
    students: [
      { studentId: '3', attendanceRate: 1.0, missedSessions: 0 },
      { studentId: 'S004', attendanceRate: 0.88, missedSessions: 2 },
    ],
  },
  {
    id: 'L003',
    subject: 'Shakespearean Literature',
    code: 'ENG210',
    teacher: 'Dr. Olivia Chen',
    teacherId: '5',
    classroom: 'Room 105',
    day: 'Wednesday',
    startTime: '14:00',
    endTime: '15:30',
    status: 'pending',
    forRoles: ['admin', 'student'],
    students: [
      { studentId: '3', attendanceRate: 0.92, missedSessions: 1 },
    ],
  },
  {
    id: 'L004',
    subject: 'Faculty Meeting',
    code: 'FM001',
    teacher: 'Admin',
    teacherId: '1',
    classroom: 'Conference Hall',
    day: 'Friday',
    startTime: '10:00',
    endTime: '11:00',
    status: 'confirmed',
    forRoles: ['admin', 'teacher'],
    students: [],
  },
  {
    id: 'L005',
    subject: 'General Chemistry',
    code: 'CHEM101',
    teacher: 'Dr. Eleanor Vance',
    teacherId: '2',
    classroom: 'Lab 3',
    day: 'Monday',
    startTime: '11:00',
    endTime: '12:30',
    status: 'confirmed',
    forRoles: ['admin', 'teacher', 'student'],
    students: [
      { studentId: '3', attendanceRate: 0.98, missedSessions: 0 },
      { studentId: 'S005', attendanceRate: 0.6, missedSessions: 4 },
    ],
  },
   {
    id: 'L006',
    subject: 'Calculus II',
    code: 'MATH203',
    teacher: 'Dr. Eleanor Vance',
    teacherId: '2',
    classroom: 'Room 205',
    day: 'Wednesday',
    startTime: '09:00',
    endTime: '10:30',
    status: 'canceled',
    forRoles: ['admin', 'teacher', 'student'],
    students: [
      { studentId: '3', attendanceRate: 0.95, missedSessions: 1 },
      { studentId: 'S002', attendanceRate: 0.99, missedSessions: 0 },
    ],
  },
];

export const notifications: Notification[] = [
    {
        id: 'N001',
        title: 'Lecture Canceled',
        description: 'Calculus II (MATH203) on Wednesday at 09:00 has been canceled.',
        read: false,
        timestamp: new Date(new Date().setDate(new Date().getDate() - 1)),
    },
    {
        id: 'N002',
        title: 'New Grade Posted',
        description: 'Your grade for Quantum Physics Midterm is now available.',
        read: true,
        timestamp: new Date(new Date().setDate(new Date().getDate() - 2)),
    },
    {
        id: 'N003',
        title: 'Room Change',
        description: 'Advanced Algorithms (CS402) will now be in Room 301.',
        read: false,
        timestamp: new Date(new Date().setDate(new Date().getDate() - 3)),
    }
]
